# Use root/example as user/password credentials

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3307:3306"
    # (this is just an example, not intended to be a production configuration)
